site_name: ПЛК IPCSA


theme:
  name: material
  custom_dir: overrides
  features:
    - glightbox
    - navigation.instant
    - navigation.tabs
  
    
  favicon: img/logo.png 
  
  language: ru
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: Red
      accent: grey

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: Red
      accent: grey 
      
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - overrides/main.js

nav:
  - Главная: index.md 
  - Руководство пользователя:
    - Модуль основной IPCSA-OG-GM: user_manual/GM.md
    - Модуль дискретного ввода IPCSA-OG-DI: user_manual/DI.md
    - Модуль дискретного вывода IPCSA-OG-DO: user_manual/DO.md
    - Модуль аналогового ввода тока IPCSA-OG-AIC: user_manual/AIC.md
    - Модуль аналогового ввода термопары IPCSA-OG-AITC: user_manual/AITC.md
    - Модуль аналогового ввода термосопротивления IPCSA-OG-AITR: user_manual/AITR.md
    - Модуль аналогового вывода IPCSA-OG-AO: user_manual/AO.md
    - Модуль счета импульсов IPCSA-OG-SPPC: user_manual/SPPC.md
    - Модуль ввода дополнительного питания IPCSA-OG-SPPM: user_manual/SPPM.md
    - Модуль оконечный IPCSA-OG-SPТM: user_manual/SPTM.md
    - Модуль интерфейсный RS-485/422 IPCSA-OG-SP485/422: user_manual/SP485_422.md


    - Модуль управления драйвером шагового двигателя IPCSA-OG-SSMD: user_manual/SSMD.md
  
  - Статьи: blog/index.md


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr

plugins:
 - blog:
     authors_file: .authors.yml
 - tags:
      tags_file: tags.md
 


    

